# Generated by Django 3.0 on 2021-05-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0002_auto_20210507_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='details',
            field=models.TextField(null=True, verbose_name='التفاصيل'),
        ),
    ]
