# Generated by Django 3.0 on 2021-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0003_auto_20210507_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='اسم')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='البريد الألكترونى')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='الهاتف')),
            ],
        ),
    ]
