# Generated by Django 3.0 on 2021-10-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_payrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='الأسم')),
                ('price', models.TextField(null=True, verbose_name='التفاصيل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='الشعار')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectstate',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='projectstate',
            name='location',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='ProjectState',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, to='realstate.Product'),
        ),
        migrations.AddField(
            model_name='payrequest',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='realstate.Order'),
        ),
    ]
