# Generated by Django 3.0 on 2021-05-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='السؤال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='الأجابة')),
            ],
        ),
    ]
