# Generated by Django 3.0 on 2021-05-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسم')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='البريد الألكترونى')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الرسالة')),
                ('message', models.TextField(blank=True, null=True, verbose_name='موضوع الرسالة')),
            ],
        ),
    ]
